### ISSUE TITLE
Steam-captcha |/_-||?

### ISSUE THREAD

**Issue by manavortex** [bitlbee/bitlbee-steam#107]
Hey there, 

I'm following the steps so far - the only problem is that my captcha looks like (I've attached it). 
Any ideas except for trying later?

regards

![screen shot 2015-12-11 at 16 40 08](https://cloud.githubusercontent.com/assets/965785/11747872/e16dd880-a025-11e5-9528-70eff93ead28.png)

**Comment by jgeboski** [comment]
Try logging in again, sometimes it gets wanky. Logging in again will generate a new captcha identifier. It might also help to view the captcha from the same network address that bitlbee is using.

**Comment by manavortex** [comment]
Thank you - will try again soon and keep you posted! I appreciate your help.

**Comment by noteventhrice** [comment]
Same issue here

**Comment by dequis** [comment]
Uh, why is this still open? There's nothing we can do about the server sending crappy craptchas.

**Comment by manavortex** [comment]
I solved it by turning steam safeguard whatsnot off.

**Comment by jgeboski** [comment]
The plugin has no control over this. If you run into this issue, it may help to open the captcha image from the same IP that bitlbee is using. This can be achieved by simply `wget`ting the image on the server, and then viewing it locally. Or even using a simple SSH tunnel.
