### ISSUE TITLE
Formatting sent false

### ISSUE THREAD

**Issue by wirehack7** [bitlbee/bitlbee-steam#117]
I have the issue that before and every line a line break got sent. When looking at the message in Steam that appears:

> 21:05 - wirehack7 | mov ecx,5: 
> test 	  				 	 	 	    		  	   		  		
> 
> 21:05 - [PB]DaEngineer: Kommt an

Mention the extra characters after _test_.
When I reply via the Steam account I get a query by myself in Bitlbee, with _wirehack7@localhost.localdomain_.

Bitlbee _3.4.2+20160506+master+27-g4fe91a1-git_ runs on "_Debian GNU/Linux 8 (jessie)_".

**Comment by jgeboski** [comment]
This sounds like something with your client as I cannot reproduce this at all. Has this ever worked correctly for you? Or did you just start using the plugin?

**Comment by jgeboski** [comment]
Any update on this issue?

**Comment by wirehack7** [comment]
Oh yes, changed charset in ZNC, removed the error, thanks!

**Comment by dequis** [comment]
What charset did it have before?
