### ISSUE TITLE
can't run autogen.sh

### ISSUE THREAD

**Issue by poserman** [bitlbee/bitlbee-steam#118]
I installed the dh-autoreconf package but it won't build. 

```
./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -Im4
configure.ac:79: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:79: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
autoreconf: running: /usr/bin/autoconf --force
configure.ac:79: error: possibly undefined macro: AM_PATH_LIBGCRYPT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by dequis** [comment]
Install libgcrypt-dev or equivalent.

**Comment by poserman** [comment]
ok i got a little bit further. after that i had to install libperl-dev and libgtk2.0-dev

now i got this error: 


configure: WARNING:
***
*** The config script /usr/bin/libgcrypt-config was
*** built for x86_64-pc-linux-gnu and thus may not match the
*** used host x86_64-unknown-linux-gnu.
*** You may want to use the configure option --with-libgcrypt-prefix
*** to specify a matching config script.
***
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for BITLBEE... no
configure: error: Package requirements (bitlbee  >= 3.4) were not met:

No package 'bitlbee' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BITLBEE_CFLAGS
and BITLBEE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.



bitlbee is installed through apt-get and running

**Comment by dequis** [comment]
Install bitlbee-dev

**Comment by poserman** [comment]
sort of worked. just can't add it in bitlbee. already restarted it. 

Just a note, might be wise to add these requirements in the readme. would have saved both of us some time :P 

configure: WARNING:
***
*** The config script /usr/bin/libgcrypt-config was
*** built for x86_64-pc-linux-gnu and thus may not match the
*** used host x86_64-unknown-linux-gnu.
*** You may want to use the configure option --with-libgcrypt-prefix
*** to specify a matching config script.
***
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for BITLBEE... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating steam/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
root@vultr:~/bitlbee-steam# make
Making all in steam
make[1]: Entering directory '/root/bitlbee-steam/steam'
  CC       steam_la-steam.lo
  CC       steam_la-steam-api.lo
  CC       steam_la-steam-crypt.lo
  CC       steam_la-steam-http.lo
  CC       steam_la-steam-json.lo
  CC       steam_la-steam-user.lo
  CC       steam_la-steam-util.lo
  CCLD     steam.la
make[1]: Leaving directory '/root/bitlbee-steam/steam'
make[1]: Entering directory '/root/bitlbee-steam'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/bitlbee-steam'
root@vultr:~/bitlbee-steam# make install
Making install in steam
make[1]: Entering directory '/root/bitlbee-steam/steam'
make[2]: Entering directory '/root/bitlbee-steam/steam'
 /bin/mkdir -p '/usr/lib/bitlbee/'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   steam.la '/usr/lib/bitlbee/'
libtool: install: /usr/bin/install -c .libs/steam.so /usr/lib/bitlbee/steam.so
libtool: install: /usr/bin/install -c .libs/steam.lai /usr/lib/bitlbee/steam.la
libtool: install: warning: remember to run `libtool --finish /usr/lib/bitlbee/'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/bitlbee-steam/steam'
make[1]: Leaving directory '/root/bitlbee-steam/steam'
make[1]: Entering directory '/root/bitlbee-steam'
make[2]: Entering directory '/root/bitlbee-steam'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/bitlbee-steam'
make[1]: Leaving directory '/root/bitlbee-steam'

**Comment by jgeboski** [comment]
What distro?

**Comment by poserman** [comment]
Ubuntu Server 15.10

**Comment by jgeboski** [comment]
Use the repository: https://jgeboski.github.io/

**Comment by jgeboski** [comment]
Also, make sure you restart bitlbee and that `Protocols` in `bitlbee.conf` is commented out or includes `steam`.

**Comment by AlD** [comment]
*And* reconnect to bitlbee.

**Comment by jgeboski** [comment]
Reconnecting to bitlbee is implied when you restart it.

@poserman any update on this issue?

**Comment by AlD** [comment]
> Reconnecting to bitlbee is implied when you restart it.

You can restart bitlbee without disconnecting clients:

```
$ ps -fCbitlbee
bitlbee  17968     1  0 15:05 ?        00:00:00 /usr/sbin/bitlbee -p 6667 -P /var/run/bitlbee.pid -F
bitlbee  18349 17968  0 15:05 ?        00:00:03 /usr/sbin/bitlbee -p 6667 -P /var/run/bitlbee.pid -F

$ sudo systemctl restart bitlbee

$ ps -fCbitlbee
bitlbee  18349     1  0 15:05 ?        00:00:03 /usr/sbin/bitlbee -p 6667 -P /var/run/bitlbee.pid -F
bitlbee  23522     1  0 20:33 ?        00:00:00 /usr/sbin/bitlbee -p 6667 -P /var/run/bitlbee.pid -F
```

**Comment by jgeboski** [comment]
Closing this issue due to lack of reply.
