### ISSUE TITLE
Messages written in steam client to offline account show up in query to myself

### ISSUE THREAD

**Issue by AlD** [bitlbee/bitlbee-steam#120]
When writing messages in the native steam client to ab offline account, my messages showed up in a query with myself in bitlbee.
I would have expected them to be in a query with the other account.

I haven't familiarized myself with the code yet. If you point me at the right place to fix this, I'll look into it.

**Comment by jgeboski** [comment]
Either use a client that supports self messages or disable them in `&bitlbee`:

```
set self_messages false
```

**Comment by AlD** [comment]
Spot on, thanks as well.
