### ISSUE TITLE
Help compiling on Cygwin x64 (Windows 7)

### ISSUE THREAD

**Issue by Andrewskiz** [bitlbee/bitlbee-steam#128]
I have compiled bitlbee with purple using cygwin, and I am trying to install this plugin and the bitlbee-facebook plugin. I am running into the same error with each one and I am not sure how to proceed. For each I have cloned the git repo and ran autogen.sh, but when I run make I receive this error.

libtool:   error: can't build x86_64-unknown-cygwin shared library unless -no-undefined is specified

I tried  make LDFLAGS=-no-undefined

and receive a bunch of errors:
Making all in steam
make[1]: Entering directory '/home/Andrewski/bitlbee-steam/steam'
  CCLD     steam.la
.libs/steam_la-steam.o: In function `steam_add_deny':
/home/Andrewski/bitlbee-steam/steam/steam.c:861: undefined reference to `imcb_bu                                                                                               ddy_status'
/home/Andrewski/bitlbee-steam/steam/steam.c:861:(.text+0x28d): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `imcb_buddy_status'
.libs/steam_la-steam.o: In function `steam_eval_accounton':
/home/Andrewski/bitlbee-steam/steam/steam.c:625: undefined reference to `account                                                                                               _on'
/home/Andrewski/bitlbee-steam/steam/steam.c:625:(.text+0x4fc): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `account_on'
.libs/steam_la-steam.o: In function `steam_init':
/home/Andrewski/bitlbee-steam/steam/steam.c:674: undefined reference to `set_add                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:674:(.text+0x547): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:677: undefined reference to `set_add                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:677:(.text+0x56c): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:680: undefined reference to `set_add                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:680:(.text+0x58d): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:683: undefined reference to `set_add                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:683:(.text+0x5ae): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:686: undefined reference to `set_add                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:686:(.text+0x5cf): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
.libs/steam_la-steam.o:/home/Andrewski/bitlbee-steam/steam/steam.c:689: more und                                                                                               efined references to `set_add' follow
.libs/steam_la-steam.o: In function `steam_init':
/home/Andrewski/bitlbee-steam/steam/steam.c:689:(.text+0x5f0): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:692:(.text+0x611): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:695:(.text+0x632): relocation trunca                                                                                               ted to fit: R_X86_64_PC32 against undefined symbol `set_add'
/home/Andrewski/bitlbee-steam/steam/steam.c:698:(.text+0x65b): additional reloca                                                                                               tion overflows omitted from the output
.libs/steam_la-steam.o: In function `steam_eval_password':
/home/Andrewski/bitlbee-steam/steam/steam.c:656: undefined reference to `set_eva                                                                                               l_account'
/home/Andrewski/bitlbee-steam/steam/steam.c:657: undefined reference to `set_res                                                                                               et'
/home/Andrewski/bitlbee-steam/steam/steam.c:660: undefined reference to `account                                                                                               _off'
/home/Andrewski/bitlbee-steam/steam/steam.c:661: undefined reference to `account                                                                                               _on'
/home/Andrewski/bitlbee-steam/steam/steam.c:663: undefined reference to `account                                                                                               _on'
.libs/steam_la-steam.o: In function `steam_eval_game_status':
/home/Andrewski/bitlbee-steam/steam/steam.c:638: undefined reference to `is_bool                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:647: undefined reference to `bool2in                                                                                               t'
.libs/steam_la-steam.o: In function `steam_req_error':
/home/Andrewski/bitlbee-steam/steam/steam.c:95: undefined reference to `imcb_err                                                                                               or'
/home/Andrewski/bitlbee-steam/steam/steam.c:99: undefined reference to `imc_logo                                                                                               ut'
.libs/steam_la-steam.o: In function `steam_cb_user_search':
/home/Andrewski/bitlbee-steam/steam/steam.c:590: undefined reference to `imcb_er                                                                                               ror'
/home/Andrewski/bitlbee-steam/steam/steam.c:600: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:607: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:608: undefined reference to `imcb_lo                                                                                               g'
.libs/steam_la-steam.o: In function `steam_cb_auth':
/home/Andrewski/bitlbee-steam/steam/steam.c:274: undefined reference to `set_set                                                                                               int'
/home/Andrewski/bitlbee-steam/steam/steam.c:275: undefined reference to `set_set                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:276: undefined reference to `set_set                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:277: undefined reference to `set_set                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:278: undefined reference to `set_set                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:295: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:303: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:305: undefined reference to `account                                                                                               _off'
/home/Andrewski/bitlbee-steam/steam/steam.c:289: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:290: undefined reference to `imcb_lo                                                                                               g'
.libs/steam_la-steam.o: In function `steam_user_status':
/home/Andrewski/bitlbee-steam/steam/steam.c:169: undefined reference to `imcb_bu                                                                                               ddy_status'
/home/Andrewski/bitlbee-steam/steam/steam.c:127: undefined reference to `imcb_bu                                                                                               ddy_status'
/home/Andrewski/bitlbee-steam/steam/steam.c:145: undefined reference to `imcb_bu                                                                                               ddy_status'
/home/Andrewski/bitlbee-steam/steam/steam.c:119: undefined reference to `imcb_bu                                                                                               ddy_by_handle'
.libs/steam_la-steam.o: In function `steam_cb_friends':
/home/Andrewski/bitlbee-steam/steam/steam.c:333: undefined reference to `bee_use                                                                                               r_by_handle'
/home/Andrewski/bitlbee-steam/steam/steam.c:341: undefined reference to `bee_use                                                                                               r_by_handle'
/home/Andrewski/bitlbee-steam/steam/steam.c:336: undefined reference to `imcb_ad                                                                                               d_buddy'
/home/Andrewski/bitlbee-steam/steam/steam.c:337: undefined reference to `imcb_bu                                                                                               ddy_nick_hint'
/home/Andrewski/bitlbee-steam/steam/steam.c:338: undefined reference to `imcb_re                                                                                               name_buddy'
/home/Andrewski/bitlbee-steam/steam/steam.c:325: undefined reference to `imcb_co                                                                                               nnected'
.libs/steam_la-steam.o: In function `steam_user_msg':
/home/Andrewski/bitlbee-steam/steam/steam.c:256: undefined reference to `imcb_ad                                                                                               d_buddy'
/home/Andrewski/bitlbee-steam/steam/steam.c:257: undefined reference to `imcb_bu                                                                                               ddy_nick_hint'
/home/Andrewski/bitlbee-steam/steam/steam.c:258: undefined reference to `imcb_re                                                                                               name_buddy'
/home/Andrewski/bitlbee-steam/steam/steam.c:189: undefined reference to `set_fin                                                                                               d'
/home/Andrewski/bitlbee-steam/steam/steam.c:217: undefined reference to `imcb_bu                                                                                               ddy_msg'
/home/Andrewski/bitlbee-steam/steam/steam.c:205: undefined reference to `imcb_bu                                                                                               ddy_by_handle'
/home/Andrewski/bitlbee-steam/steam/steam.c:222: undefined reference to `imcb_bu                                                                                               ddy_typing'
/home/Andrewski/bitlbee-steam/steam/steam.c:229: undefined reference to `imcb_bu                                                                                               ddy_by_handle'
/home/Andrewski/bitlbee-steam/steam/steam.c:236: undefined reference to `imcb_bu                                                                                               ddy_typing'
/home/Andrewski/bitlbee-steam/steam/steam.c:248: undefined reference to `imcb_re                                                                                               move_buddy'
/home/Andrewski/bitlbee-steam/steam/steam.c:252: undefined reference to `imcb_as                                                                                               k_auth'
/home/Andrewski/bitlbee-steam/steam/steam.c:208: undefined reference to `imcb_bu                                                                                               ddy_typing'
.libs/steam_la-steam.o: In function `steam_cb_msgs':
/home/Andrewski/bitlbee-steam/steam/steam.c:456: undefined reference to `bee_use                                                                                               r_by_handle'
.libs/steam_la-steam.o: In function `steam_cb_user_info_nicks':
/home/Andrewski/bitlbee-steam/steam/steam.c:525: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:532: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:548: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:554: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:558: undefined reference to `imcb_lo                                                                                               g'
.libs/steam_la-steam.o:/home/Andrewski/bitlbee-steam/steam/steam.c:562: more und                                                                                               efined references to `imcb_log' follow
.libs/steam_la-steam.o: In function `steam_cb_logon':
/home/Andrewski/bitlbee-steam/steam/steam.c:407: undefined reference to `set_set                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:408: undefined reference to `imcb_lo                                                                                               g'
.libs/steam_la-steam.o: In function `steam_cb_key':
/home/Andrewski/bitlbee-steam/steam/steam.c:383: undefined reference to `set_get                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:384: undefined reference to `set_get                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:386: undefined reference to `imcb_lo                                                                                               g'
.libs/steam_la-steam.o: In function `steam_data_new':
/home/Andrewski/bitlbee-steam/steam/steam.c:50: undefined reference to `imcb_new                                                                                               '
/home/Andrewski/bitlbee-steam/steam/steam.c:53: undefined reference to `set_gets                                                                                               tr'
/home/Andrewski/bitlbee-steam/steam/steam.c:54: undefined reference to `set_gets                                                                                               tr'
/home/Andrewski/bitlbee-steam/steam/steam.c:55: undefined reference to `set_gets                                                                                               tr'
/home/Andrewski/bitlbee-steam/steam/steam.c:56: undefined reference to `set_getb                                                                                               ool'
.libs/steam_la-steam.o: In function `steam_login':
/home/Andrewski/bitlbee-steam/steam/steam.c:710: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:728: undefined reference to `imcb_lo                                                                                               g'
/home/Andrewski/bitlbee-steam/steam/steam.c:713: undefined reference to `set_get                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:717: undefined reference to `set_get                                                                                               str'
/home/Andrewski/bitlbee-steam/steam/steam.c:721: undefined reference to `set_get                                                                                               int'
/home/Andrewski/bitlbee-steam/steam/steam.c:722: undefined reference to `imcb_lo                                                                                               g'
.libs/steam_la-steam.o: In function `steam_add_buddy':
/home/Andrewski/bitlbee-steam/steam/steam.c:835: undefined reference to `imcb_er                                                                                               ror'
.libs/steam_la-steam.o: In function `steam_cb_auth':
/home/Andrewski/bitlbee-steam/steam/steam.c:299: undefined reference to `imc_log                                                                                               out'
/home/Andrewski/bitlbee-steam/steam/steam.c:306: undefined reference to `account                                                                                               _on'
.libs/steam_la-steam.o: In function `init_plugin':
/home/Andrewski/bitlbee-steam/steam/steam.c:981: undefined reference to `registe                                                                                               r_protocol'
.libs/steam_la-steam.o:steam.c:(.rdata$.refptr.SET_INVALID[.refptr.SET_INVALID]+                                                                                               0x0): undefined reference to `SET_INVALID'
.libs/steam_la-steam-api.o: In function `steam_api_req_cb':
/home/Andrewski/bitlbee-steam/steam/steam-api.c:349: undefined reference to `jso                                                                                               n_value_free'
.libs/steam_la-steam-api.o: In function `steam_api_cb_auth':
/home/Andrewski/bitlbee-steam/steam/steam-api.c:488: undefined reference to `jso                                                                                               n_value_free'
.libs/steam_la-steam-api.o: In function `steam_api_req_user_accept':
/home/Andrewski/bitlbee-steam/steam/steam-api.c:1129: undefined reference to `ur                                                                                               l_set'
.libs/steam_la-steam-api.o: In function `steam_api_req_user_ignore':
/home/Andrewski/bitlbee-steam/steam/steam-api.c:1209: undefined reference to `ur                                                                                               l_set'
.libs/steam_la-steam-api.o: In function `steam_api_cb_user_remove':
/home/Andrewski/bitlbee-steam/steam/steam-api.c:1424: undefined reference to `bo                                                                                               ol2int'
.libs/steam_la-steam-api.o: In function `steam_api_req_user_info_nicks':
/home/Andrewski/bitlbee-steam/steam/steam-api.c:1411: undefined reference to `ur                                                                                               l_set'
.libs/steam_la-steam-http.o: In function `steam_http_req_close':
/home/Andrewski/bitlbee-steam/steam/steam-http.c:287: undefined reference to `b_                                                                                               event_remove'
/home/Andrewski/bitlbee-steam/steam/steam-http.c:304: undefined reference to `ht                                                                                               tp_close'
.libs/steam_la-steam-http.o: In function `steam_http_req_done':
/home/Andrewski/bitlbee-steam/steam/steam-http.c:438: undefined reference to `b_                                                                                               timeout_add'
.libs/steam_la-steam-http.o: In function `steam_http_uri_escape':
/home/Andrewski/bitlbee-steam/steam/steam-http.c:607: undefined reference to `ht                                                                                               tp_encode'
.libs/steam_la-steam-http.o: In function `steam_http_req_send':
/home/Andrewski/bitlbee-steam/steam/steam-http.c:574: undefined reference to `ht                                                                                               tp_dorequest'
/home/Andrewski/bitlbee-steam/steam/steam-http.c:594: undefined reference to `b_                                                                                               timeout_add'
.libs/steam_la-steam-http.o: In function `steam_http_uri_unescape':
/home/Andrewski/bitlbee-steam/steam/steam-http.c:622: undefined reference to `ht                                                                                               tp_decode'
.libs/steam_la-steam-json.o: In function `steam_json_new':
/home/Andrewski/bitlbee-steam/steam/steam-json.c:44: undefined reference to `jso                                                                                               n_parse_ex'
.libs/steam_la-steam-json.o: In function `steam_json_val_chk':
/home/Andrewski/bitlbee-steam/steam/steam-json.c:104: undefined reference to `js                                                                                               on_o_get'
.libs/steam_la-steam-user.o: In function `steam_user_chans_msg':
/home/Andrewski/bitlbee-steam/steam/steam-user.c:65: undefined reference to `irc                                                                                               _channel_has_user'
/home/Andrewski/bitlbee-steam/steam/steam-user.c:66: undefined reference to `irc                                                                                               _send_msg'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:423: steam.la] Error 1
make[1]: Leaving directory '/home/Andrewski/bitlbee-steam/steam'
make: *** [Makefile:386: all-recursive] Error 1

Pretty much the same result as with the facebook plugin. I realize this is a pebkac issue but any help would be appreciated.

**Comment by dequis** [comment]
The main issue here was that the plugin didn't have anything to link to, that's fixed with this bitlbee commit: https://github.com/bitlbee/bitlbee/commit/54b2a367f6986a74fd6b4e50a0ae2c5cdb3a40cb (only learned about this recently thanks to someone in #cygwin)

The other, less exciting issue (no-undefined), is fixed by f49e0e5222184cfd7f5452a7ea82d3b2c425b8fc in this repo

So just building the latest git versions of both bitlbee and this plugin should be enough to get it working. When building this new version of bitlbee it's important to repeat the whole process from `./configure` to `make install-dev` as there were important changes to bitlbee.pc
