### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by drvink** [bitlbee/bitlbee-steam#133]
Seems to have started happening in the past few days. I confirmed that I'm able to log in to my Steam account, and I haven't touched the Bitlbee config at all, so something must have changed with Steam.

If I can supply any debug/logging information somehow, let me know and I'll provide it.

**Comment by drvink** [comment]
Never mind, I'm an idiot and read the README--just had to reset my token and reauthenticate.

**Comment by usvi** [comment]
I keep coming here always via search engines when I forget how to resolve this. It goes like this:

1. account steam off
2. account steam set -del token
3. account steam on
4. Go check your email for the auth code
5. account steam set authcode 4UTHC

It's fixed.
